### PR TITLE
Adding as_colmns option

### PR DESCRIPTION
**Pull request by phochste**
I need to process XLS files that have such bad header names (containing new lines, slashes, spaces, parentheses, etc) that it is impossible to manipulate with Catmandu fixes. The as_columns option translates all the column names into coordinates: A,B,C,D, etc.

### CODE REVIEW

**Comment by nichtich** [comment]
The corresponding option in [Catmandu::Exporter::CSV](https://metacpan.org/pod/Catmandu::Exporter::CSV) and [Catmandu::Exporter::XLS](https://metacpan.org/pod/Catmandu::Exporter::XLS)  is `header`, in [Catmandu::Exporter::Table](https://metacpan.org/pod/Catmandu::Exporter::Table) it is named `columns`. We should stick to one common name for tabular-data importers and exporters.

**Comment by jorol** [comment]
In the synopsis of  [Catmandu::Exporter::Table](https://metacpan.org/pod/Catmandu::Exporter::Table) you use `header`

    catmandu convert CSV to Table --fields id,name --header ID,Name < sample.csv

in the configuration section `columns`

Table output can be controlled with the options fields, columns, widths, and condense

**Comment by phochste** [comment]
"Header" has also another meaning in Catmandu::Exporter::XLS(X): it is a boolean there to switch on/off headers. Same is true in Catmandu::Exporter::CSV. I don't know if this double meaning is valid in  Catmandu::Exporter::Table

**Comment by jorol** [comment]
With the `header` option of [Catmandu::Importer::CSV](https://metacpan.org/pod/Catmandu::Importer::CSV) you could something like this:

```terminal
$ printf "a,b,c\n1,2,3" | catmandu convert CSV --header 1 --fields x,y,z to YAML
---
x: '1'
y: '2'
z: '3'
...
```

Would that be a solution for the XLS(X) importer?

**Comment by nichtich** [comment]
In fact Catmandu::Exporter::Table uses `columns` but the documentation says `header`. `fields` is used to specify field names and `columns`/`header`/`as_header` to specify the column names. How about:

* `header`: toggle column names on/off
* `columns`: column names in the header. Set to field names by default. Used as new field names for importers
* `fields`: field names

So for Catmandu::Importer::XLS the option should be named `columns` instead of `as_columns`. And Catmandu::Exporter::XLS should also get a `columns` option.

**Comment by jorol** [comment]
See discussion at pr #2

**Comment by jorol** [comment]
>  And Catmandu::Exporter::XLS should also get a columns option.

Do we really need this option for the XLS(X) exporters, as software like Excel, Calc, ... already provides column coordinates by default?

**Comment by nichtich** [comment]
Option `columns` is meant to controll column names in the header, for instance "Herausgeber" for field "publisher". This is useful for all tabular exporters.

**Pull request merged**
